newser/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^profile$', views.index, name='profile'),
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout')
]

newser/backend/urls.py
from django.conf.urls import url
from rest_framework import routers
from .views import ArticleViewSet, test


router = routers.DefaultRouter()
router.register(r'article', ArticleViewSet, base_name="article")
urlpatterns = [
    url(r'^test/$', test),
]
urlpatterns += router.urls

newser/newser/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from backend.urls import urlpatterns

urlpatterns = [
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^viewer/', include('viewer.urls', namespace='viewer')),
    url(r'^backend/', include(urlpatterns, namespace='backend')),
    url(r'^admin/', admin.site.urls),
    url('', include('social.apps.django_app.urls', namespace='social')),
]

newser/viewer/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

newser/accounts/models.py
# coding: utf-8
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    image_url = models.URLField('画像URL', blank=True)

newser/backend/models.py
from django.db import models
from django.utils.timezone import now, utc
from django.conf import settings

class RssFeeds(models.Model):
    """
    RSS Feeds
    """

    url = models.URLField(max_length=2000)
    name = models.CharField(max_length=1000)
    valid = models.BooleanField(default=True)

    def __str__(self):
        return "{}:{}".format(self.name, self.valid)

    @classmethod
    def get_valid_feeds(cls):
        """
        フィードの一覧について有効になっているものだけ戻す
        :return:
        """
        return cls.objects.filter(valid=True)

    def get_max_timestamp(self):
        """
        関連フィードの最大の更新時間
        :return:
        """
        return self.related_articles.aggregate(models.Max('timestamp'))["timestamp__max"]


class Articles(models.Model):
    """
    記事
    """

    url = models.URLField(max_length=2000, primary_key=True)
    # base64
    thumbnail = models.CharField(max_length=20000, default=None, null=True)
    title = models.CharField(max_length=1000)
    summary = models.CharField(max_length=2000)
    timestamp = models.DateTimeField(default=now)
    source = models.ForeignKey(RssFeeds, name="source", related_name="related_articles", default=None, null=True)

    def __str__(self):
        return "({}){}".format(self.source, self.title)


class ReadHistories(models.Model):
    """
    読み込み履歴
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="red_article", on_delete=models.CASCADE,)
    article = models.ForeignKey(Articles, name="red_article")
    timestamp = models.DateTimeField(default=now)

newser/viewer/models.py
from django.db import models

# Create your models here.

newser/accounts/views.py
# coding:utf-8

from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    context = {
        "user": request.user
    }
    return render(request, "accounts/profile.html", context=context)

newser/backend/views.py
from django.shortcuts import render
import django_filters
from rest_framework import viewsets, filters
from .models import Articles
from .serializer import ArticleSerializer
# Create your views here.


def test(request):
    context = {
        "user": "DEMO"
    }
    return render(request, "accounts/profile.html", context=context)


class ArticleViewSet(viewsets.ReadOnlyModelViewSet):
    serializer_class = ArticleSerializer

    def get_queryset(self):
        # ログイン済みでなければ全件戻す
        if self.request.user.id:
            # TODO
            return Articles.objects.all().order_by("-timestamp")
        else:
            return Articles.objects.all().order_by("-timestamp")

newser/viewer/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    context = {
        "user": request.user
    }
    return render(request, "viewer/contents/list.html", context=context)

newser/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block title%}
site login
{% endblock%}


{% block content %}

{% if form.errors  %}
    <div class="alert alert-danger" role="alert">
        <p>Your usernamne and password didn't match. Please try again.</p>
    </div>
{% endif %}

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title text-center">Log-in to mysite</h3>
    </div>
    <a href="{% url 'social:begin' 'twitter' %}?next={{ next}}">Login with Twitter</a> <br/>
    <a href="{% url 'social:begin' 'facebook' %}?next={{ next}}">Login with Facebook</a>
</div>
{% endblock %}

newser/accounts/templates/accounts/logout.html
{% extends "base.html" %}

{% block title%}
site logout
{% endblock%}


{% block content %}

<div class="panel panel-primary">

    <a href="{% url 'accounts:login' %}" >re login? </a>

</div>

{% endblock %}

newser/accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block title%}
Profile
{% endblock%}


{% block content %}

Welcome to {{ user.username }}

<a href="{% url 'viewer:index' %}"> viewer </a><br/>

<a href="{% url 'accounts:logout' %}"> logout </a>

{% endblock %}

newser/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block extraheader %}
    {# append css or javascript #}
    {% endblock %}
</head>
<body>
{% block content %}

{% endblock%}
</body>
</html>

newser/viewer/templates/viewer/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A portfolio template that uses Material Design Lite.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">

    <title>{% block title %}VIEWER{% endblock %}</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.light_green-deep_purple.min.css" />
    <link rel="stylesheet" href='{% static "css/styles.css" %}' />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/riot@3.6/riot+compiler.min.js"></script>

    {% block extraheader %}
    {% endblock %}
</head>
<body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header mdl-layout__header--waterfall portfolio-header">
            <div class="mdl-layout__header-row portfolio-logo-row">
                <span class="mdl-layout__title">
                    <div class="portfolio-logo"></div>
                    <span class="mdl-layout__title">welcome to {{ user.username }}</span>
                </span>
            </div>

            <div class="mdl-layout__header-row portfolio-navigation-row mdl-layout--large-screen-only">
                <nav class="mdl-navigation mdl-typography--body-1-force-preferred-font">
                    <a class="mdl-navigation__link is-active" href="{% url 'accounts:profile' %}">Profile</a>
                </nav>
            </div>
        </header>
        <div class="mdl-layout__drawer mdl-layout--small-screen-only">
            <nav class="mdl-navigation mdl-typography--body-1-force-preferred-font">
                <a class="mdl-navigation__link is-active" href="{% url 'accounts:profile' %}">Profile</a>
            </nav>
        </div>
{% block content %}

{% endblock%}

    </div>
<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
</body>
</html>

newser/viewer/templates/viewer/contents/list.html
{% extends "viewer/base.html" %}
{% load staticfiles %}

{% block title%}
NEWS LIST
{% endblock%}
{% block extraheader %}
<link rel="stylesheet" href='{% static "css/styles.css" %}' />
<script type="text/javascript" src='{% static "js/list.js"%}'></script>
<script type="riot/tag" src='{% static "js/news_card.html"%}'></script>


{% endblock %}
{% block content %}
    <main class="mdl-layout__content">
        <news-card></news-card>
    </main>
<script>

var NEWS_CARD = null;
var NEXT_API_URL = null;
var IS_LOADING = false;
riot.compile(function() {
    // initialize
    axios.get('/backend/article.json')
        .then(function (response) {
            //console.log(JSON.stringify(response, null, 4));
            var articleList = response.data.results;
            NEWS_CARD=riot.mount("news-card", {
                newsDataList: articleList,
                next : response.data.next
            })[0];
            NEXT_API_URL = response.data.next;
            console.log(NEWS_CARD);
        }).catch(function (error) {
            console.log(error);
        });
})

var content = document.querySelector(".mdl-layout__content");
content.addEventListener("scroll", function(e){
    console.log(content.scrollTop, content.scrollHeight);
    if(!IS_LOADING && content.scrollTop >  content.scrollHeight * 0.7 && NEXT_API_URL){
        // 乱発防止用のフラグ
        IS_LOADING = true;
        console.log("load", NEXT_API_URL);
        axios.get(NEXT_API_URL)
            .then(function (response) {
            //console.log(JSON.stringify(response, null, 4));
            var articleList = response.data.results;
            NEWS_CARD.addArticle(articleList);
            NEXT_API_URL = response.data.next;
            IS_LOADING = false;
        }).catch(function (error) {
            console.log(error);
        });
    }
}, false);


</script>

{% endblock %}